### ISSUE TITLE
Ajouter des amis

### ISSUE THREAD

**Issue by Saodus** [HE-Arc/T-Caps#6]
Permettre à un utilisateur d'ajouter des personnes à sa liste d'ami

**Comment by Saodus** [comment]
Ajout d'ami en fonction de leurs username fonctionnelle. 

TODO
Style

**Comment by max15015** [comment]
J'ai corrigé un bug avec les migrations. Il y avait deux migrations avec create de la même table. J'en ai gardé le plus récent des deux car ils étaient très similaire
